# Site
name: "HackHPC Mentors Gallery"
title: "HackHPC Mentors Gallery"
description: "Inspiring the Next Wave of HPC Pioneers: Our Mentor Gallery"
logo: 'assets/images/mentorsgallery-logo-horiz.svg'
favicon: 'assets/images/logo.png'
url: https://hackhpc.github.io
baseurl: /mentorgallery
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sal:
    name: Je'aime 
    display_name: Powell
    gravatar: 005a09776cc56560a5598e49c454329fb5ea324503ba5190ca710d59d71a3c08
    email: jeaimehp@gmail.com
    web: https://jeaimehp.github.io
    twitter: http://twitter.com/jeaimehp
    description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  john:
    name: John
    display_name: John    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: > 
      "Je’aime Powell’s professional journey includes significant roles in IT, from 
      research institutions to his current position at Omnibond Systems. His diverse 
      experience and ability to adapt to new technologies have made him a leader in 
      collaborative environments, focusing on HPC and IoT applications."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 18
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
